### ISSUE TITLE
Invalid signature when using "custom_fields"

### ISSUE THREAD

**Issue by jrubins** [calvinfroedge/Aweber-API-NodeJS-Library#2]
When trying to subscribe a user, if you include the `custom_fields` field, you will get a 401 response from Aweber with the message:

```
Invalid signature. Expected signature base string: ...
```

Seems like this is because the method for generating the OAuth 1.0 signature does not consider nested objects in the params.

**Comment by calvinfroedge** [comment]
Hi @jrubins, I am not actively maintaining this, but if you submit a PR I will merge quickly.

**Comment by jrubins** [comment]
Turns out no PR is needed.

If you're using custom fields, you have to `JSON.stringify` the object. For example:

```
apiClient.request('post', '.../subscribers', {
    'ws.op': 'create',
    email: 'myemail@gmail.com',
    custom_fields: JSON.stringify({
        my_custom_field_key: 'Custom field value'
    })
}, ...
```

@calvinfroedge feel free to close this issue.
